FROM node:14.14-alpine
WORKDIR /app
COPY . .
RUN npm i --production
RUN npm uninstall framer-motion
RUN npm install framer-motion@3.10.6
RUN npm install @emotion/react
RUN npm install @emotion/styled
CMD npm run build