version: "3.8"
services:
 api:
  build: ./api
  environment:
   - NODE_ENV=$API_NODE_ENV
   - PORT=$API_PORT
  ports:
   - $API_PORT:$API_PORT
  volumes:
   - ./api:/app
   - /app/node_modules
 ui:
  build: ./client
  environment:
   - NODE_ENV=$UI_NODE_ENV
   - PORT=$UI_PORT
   - REACT_APP_API_HOST
  ports:
   - $UI_PORT:$UI_PORT
  volumes:
   - ./client:/app
   - /app/node_modules
  stdin_open: true
